export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

export const LOGOUT = "LOGOUT";

//USER
export const GET_LOGGED_USER = "GET_LOGGED_USER";
export const GET_LOGGED_USER_SUCCESS = "GET_LOGGED_USER_SUCCESS";
export const GET_LOGGED_USER_ERROR = "GET_LOGGED_USER_ERROR";

export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const UPDATE_PROFILE = "GET_USER";
export const UPDATE_PROFILE_SUCCESS = "GET_USER_SUCCESS";
export const UPDATE_PROFILE_ERROR = "GET_USER_ERROR";
export const UPDATE_PROFILE_REVERT = "UPDATE_PROFILE_REVERT";

//POSTS
export const GET_ALL_POSTS = "GET_ALL_POSTS";
export const GET_ALL_POSTS_SUCCESS= "GET_ALL_POSTS_SUCCESS";
export const GET_ALL_POSTS_ERROR = "GET_ALL_POSTS_ERROR";

export const GET_MY_POSTS = "GET_MY_POSTS";
export const GET_MY_POSTS_SUCCESS = "GET_MY_POSTS_SUCCESS";
export const GET_MY_POSTS_ERROR = "GET_MY_POSTS_ERROR";

export const GET_POST = "GET_POST";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_ERROR = "GET_POST_ERROR";


export const GET_USER_POSTS = "GET_USER_POSTS";
export const GET_USER_POSTS_SUCCESS = "GET_USER_POSTS_SUCCESS";
export const GET_USER_POSTS_ERROR = "GET_USER_POSTS_ERROR";


//AUTH 
export const UPLOAD_POST = "UPLOAD_POST";
export const UPLOAD_POST_SUCCESS = "UPLOAD_POST_SUCCESS";
export const UPLOAD_POST_ERROR = "UPLOAD_POST_ERROR";

export const DELETE_POST = "DELETE_POST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_ERROR = "DELETE_POST_ERROR";

export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";
export const DELETE_ALL_NOTIFICATION = "DELETE_ALL_NOTIFICATION";


export const EDIT_POST = "EDIT_POST";
export const EDIT_POST_SUCCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_ERROR = "EDIT_POST_ERROR";

export const LIKE_POST = "LIKE_POST";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_ERROR = "LIKE_POST_ERROR";

export const COMMENT = "COMMENT";
export const COMMENT_SUCCESS = "COMMENT_SUCCESS";
export const COMMENT_ERROR = "COMMENT_ERROR";

export const REVERT_USER = "REVERT_USER";
export const REVERT_POST = "REVERT_POST";
export const REVERT_AUTH = "REVERT_AUTH";

export const USER_NOTIFICATION = "USER_NOTIFICATION";
export const USER_NOTIFICATION_SUCCESS = "USER_NOTIFICATION_SUCCESS";
export const USER_NOTIFICATION_ERROR = "USER_NOTIFICATION_ERROR";












